### ISSUE TITLE
Update test history ?

### ISSUE THREAD

**Issue by smarchandon** [SmallTestHQ/SmallTest#1]
Hello,
We are evaluating SmallTest and find it very simple / perfect fit for what we want... but there a serious showstopper. Once a test is created and the status is set, no way to update it anymore!

Ideally the user should be able to modify both content and result. Is this possible ? and How?

**Comment by SmallTestHQ** [comment]
@smarchandon,

I sincerely apologize for the late response - I accidentally turned off the email notification. This is a great feedback and we will release it this week. If you choose to continue using our product, please let me know and I will be more than happy to offer you a discount.

Thank you and best regards,
SmallTest Support

**Comment by smarchandon** [comment]
Great to hear from you, I'm looking forward for this little Enh... my trial license expires soon, I'll try to ask for a second one ...

**Comment by SmallTestHQ** [comment]
@smarchandon,

We are testing the new version and will release it in two days. Regarding the evaluation, JIRA lets you create trial license six times so it should be fine for you to create a second one. If you have any problem, please let us know and we will create an evaluation version for you.

Regards,
SmallTest Support

**Comment by SmallTestHQ** [comment]
@smarchandon,

The version 4.3.0 has been released with the ability to edit existing test logs. We are looking forward to your feedback.

Thank you so much for trying our product!

Sincerely,
SmallTest Support

**Comment by smarchandon** [comment]
We immediately tested and it's exactly what we are looking for. I'm closing the ticket... to be continued within JIRA
