### ISSUE TITLE
At least one issue type required per project

### ISSUE THREAD

**Issue by smarchandon** [SmallTestHQ/SmallTest#2]
Hello,

We are starting to use the Add Ons, and stuble on a simple issue : for some projects (admin ones indeed), we don't want simple test to be visible at all... but in order to save config, at least one issue type must be selected in config. Could you please allow all issue types to be switch off. 

Also, please change the icon in the project side bar, you are using the same sprocket icon then "project settings", that's confusing. 

Regards

Stéphane

**Comment by SmallTestHQ** [comment]
Stéphane,

Thank you for the feedback. We will release a new version this week to address your issues.

Regards,
SmallTest Support

**Comment by SmallTestHQ** [comment]
Stéphane,

Version 4.4 has been released with the fixes for your issues - we hope it will help. Thank you again for your feedback, and we are looking forward to getting more suggestions from you.

Regards,
SmallTest Support
