### ISSUE TITLE
Nb items per page (inputtext field) in 4.5.0 create problem in main page

### ISSUE THREAD

**Issue by smarchandon** [SmallTestHQ/SmallTest#4]
Hello, we just installed 4.5.0. when we enter a new worklog in JIRA, in the ticket main screen, we get an error message in browser "You are about the leave page, do you want to refresh ?" in Chrome.

I think this is linked to the input text field "nb records per page", as an input text, and a worklog screen refresh, Chrome is worried some data may be lost in the form and fires an error message.

could you please provide a fix ? We had to disable the adds ons, too many troubles with worklogs entries.

**Comment by SmallTestHQ** [comment]
Hi,

Sorry for the issue. We will provide a fix in a few hours.

Sincerely,
SmallTest Support

**Comment by SmallTestHQ** [comment]
Stéphane,

We've released version 4.5.2 to fix the bug. If you have any other issues, we will resolve them ASAP.

We would like to apologize again for the bug.

Thank you and best regards,
SmallTest Support

**Comment by smarchandon** [comment]
confirmed it works, ticket closed
